// EN FR DE NL fr-BE nl-BE lb
export const locales=['en','fr','fr-BE','de','nl','nl-BE','lb'];
const data={
  en:{shop:'Shop',beranda:'Home',stok:'Stock',kasir:'POS',laporan:'Report',profil:'Profile',openKasir:'Open POS',addProd:'Add Product',today:'Today omzet',trx:'Transactions',low:'Low Stock',recent:'Recent',setupWero:'Setup Wero QR',scanStore:'Scan Static QR to fill Store ID',cash:'Cash',weroInv:'Wero Invoice',weroStatic:'Wero Static',debt:'Debt',makeQr:'Make Dynamic QR',scanBarcode:'Scan Barcode',voice:'Voice',hutang:'Debts',printPdf:'Print / PDF',bayar:'Pay',total:'Total',kembalian:'Change',customer:'Customer Name'},
  fr:{shop:'Boutique',beranda:'Accueil',stok:'Stock',kasir:'Caisse',laporan:'Rapports',profil:'Profil',openKasir:'Ouvrir caisse',addProd:'Ajouter produit',today:"CA aujourd'hui",trx:'Transactions',low:'Stock faible',recent:'Récents',setupWero:'Configurer Wero QR',scanStore:'Scanner QR statique pour ID Magasin',cash:'Espèces',weroInv:'Facture Wero',weroStatic:'Wero Statique',debt:'Dette',makeQr:'Créer QR dynamique',scanBarcode:'Scanner code-barres',voice:'Voix',hutang:'Dettes',printPdf:'Imprimer / PDF',bayar:'Payer',total:'Total',kembalian:'Monnaie',customer:'Nom Client'},
  de:{shop:'Laden',beranda:'Start',stok:'Lager',kasir:'Kasse',laporan:'Berichte',profil:'Profil',openKasir:'Kasse öffnen',addProd:'Produkt hinzufügen',today:'Umsatz heute',trx:'Transaktionen',low:'Wenig Bestand',recent:'Letzte',setupWero:'Wero QR einrichten',scanStore:'Statischen QR scannen für Store ID',cash:'Bar',weroInv:'Wero Rechnung',weroStatic:'Wero Statisch',debt:'Schulden',makeQr:'Dynamischen QR erstellen',scanBarcode:'Barcode scannen',voice:'Stimme',hutang:'Schulden',printPdf:'Drucken / PDF',bayar:'Bezahlen',total:'Gesamt',kembalian:'Wechselgeld',customer:'Kundenname'},
  nl:{shop:'Winkel',beranda:'Home',stok:'Voorraad',kasir:'Kassa',laporan:'Rapporten',profil:'Profiel',openKasir:'Open Kassa',addProd:'Product toevoegen',today:'Omzet vandaag',trx:'Transacties',low:'Lage voorraad',recent:'Recent',setupWero:'Stel Wero QR in',scanStore:'Scan statische QR voor Store ID',cash:'Contant',weroInv:'Wero Factuur',weroStatic:'Wero Statisch',debt:'Schuld',makeQr:'Maak dynamische QR',scanBarcode:'Scan barcode',voice:'Stem',hutang:'Schulden',printPdf:'Print / PDF',bayar:'Betalen',total:'Totaal',kembalian:'Wisselgeld',customer:'Klantnaam'},
  'fr-BE':{shop:'Boutique BE',beranda:'Accueil',stok:'Stock',kasir:'Caisse',laporan:'Rapports',profil:'Profil',openKasir:'Ouvrir caisse',addProd:'Ajouter produit',today:"CA aujourd'hui",trx:'Transactions',low:'Stock faible',recent:'Récents',setupWero:'Configurer Wero QR',scanStore:'Scanner QR statique',cash:'Espèces',weroInv:'Facture Wero',weroStatic:'Wero Statique',debt:'Dette',makeQr:'Créer QR dynamique',scanBarcode:'Scanner code-barres',voice:'Voix',hutang:'Dettes',printPdf:'Imprimer / PDF',bayar:'Payer',total:'Total',kembalian:'Monnaie',customer:'Nom Client'},
  'nl-BE':{shop:'Winkel BE',beranda:'Home',stok:'Voorraad',kasir:'Kassa',laporan:'Rapporten',profil:'Profiel',openKasir:'Open Kassa',addProd:'Product toevoegen',today:'Omzet vandaag',trx:'Transacties',low:'Lage voorraad',recent:'Recent',setupWero:'Stel Wero QR in',scanStore:'Scan statische QR',cash:'Contant',weroInv:'Wero Factuur',weroStatic:'Wero Statisch',debt:'Schuld',makeQr:'Maak dynamische QR',scanBarcode:'Scan barcode',voice:'Stem',hutang:'Schulden',printPdf:'Print / PDF',bayar:'Betalen',total:'Totaal',kembalian:'Wisselgeld',customer:'Klantnaam'},
  lb:{shop:'Buttek',beranda:'Heem',stok:'Stock',kasir:'Keess',laporan:'Rapporten',profil:'Profil',openKasir:'Keess opmaachen',addProd:'Produkt derbäi',today:'Ëmsaz haut',trx:'Transaktiounen',low:'Wéineg Stock',recent:'Rezent',setupWero:'Wero QR astellen',scanStore:'Statesche QR scannen',cash:'Boer',weroInv:'Wero Rechnung',weroStatic:'Wero Statesch',debt:'Schold',makeQr:'Dynamesch QR maachen',scanBarcode:'Barcode scannen',voice:'Stëmm',hutang:'Scholden',printPdf:'Drécken / PDF',bayar:'Bezuelen',total:'Total',kembalian:'Wiesselgeld',customer:'Client Numm'},
};
export function detectLocale(){ const l=(navigator.language||'en').toLowerCase(); if(l.startsWith('lb'))return 'lb'; if(l==='fr-be')return 'fr-BE'; if(l==='nl-be')return 'nl-BE'; if(l.startsWith('fr'))return 'fr'; if(l.startsWith('de'))return 'de'; if(l.startsWith('nl'))return 'nl'; return 'en'; }
let cur=localStorage.getItem('wero_locale')||detectLocale();
export function t(k){ const d=data[cur]||data.en; return d[k]||data.en[k]||k; }
export function setLocale(l){ if(!data[l])l='en'; cur=l; localStorage.setItem('wero_locale',l); }
export function getLocale(){return cur}
export function formatEur(cents){ const n=cents/100; const loc={en:'en-NL',fr:'fr-FR',de:'de-DE',nl:'nl-NL','fr-BE':'fr-BE','nl-BE':'nl-BE',lb:'lb-LU'}[cur]||'en-NL'; try{ return new Intl.NumberFormat(loc,{style:'currency',currency:'EUR'}).format(n); }catch{ return '€'+n.toFixed(2); } }
